### ISSUE TITLE
Main Nav: Home link on <= sm

### ISSUE THREAD

**Issue by jevets** [evendev/gorge-kirby#10]
> **Navigation:** Can remove ‘home’ link from medium breakpoint ­­ ‘the zipline experience’ was thinking
link to /home since this really covers the experience (and will contain more specific experience marketing text in future 2016 updates)

When running through site w/ Sara, she'd asked how to get back to home page when viewing mobile. 

I'm not sure removing home link, nor linking "zipline experience" to home, are good solutions.

Linking Zipline Experience to home page is kinda misleading... means only way to get to main /zipline page is to use a button "info" or "reserve" from home page.

Thoughts? Certainly up for discussion.

**Comment by groovyxyz** [comment]
My thinking is to turn the homepage into the 'zipline experience' page, as it will contain most of the 'good stuff' regarding the trip -- pics, videos, descriptions, so on. /Zipline being more of the logistical & fine details, won't be quite as much of a marketing page as homepage will be. 

One issue is that current /zipline has quite a bit of social likes. Also, for seo purposes, I don't want the home and /zipline to compete with each other, and don't think changing the /zipline url would be a good idea due to so many likes/links.

Let me know thoughts here -- this will need some further discussing I believe.

**Comment by jevets** [comment]
Gotcha, definitely some more discussion needed. Is worth throwing this concern in, too: 

I don't like how big the new /zipline page is, by big I mean all the tabs and their content. Been thinking about breaking that up into multiple pages instead of javascript based tabs. So if that's in order, then maybe we rework the content of the main /zipline page, possibly adding in /zipline/faqs, /zipline/requirements etc, that way /zipline stays available for seo/social

Just something to throw into the discussion.

**Comment by groovyxyz** [comment]
My vote is to leave them as tabs for now -- any updates can be approached post-launch as separate project/update.
